// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBook.Infrastructure.Data;

#nullable disable

namespace PhoneBook.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915161853_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PhoneBook.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CellPaddingMm")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultFontSizePt")
                        .HasColumnType("REAL");

                    b.Property<double>("GroupGapMm")
                        .HasColumnType("REAL");

                    b.Property<double>("GroupHeaderFontSizePt")
                        .HasColumnType("REAL");

                    b.Property<double>("HeaderFontSizePt")
                        .HasColumnType("REAL");

                    b.Property<double>("MarginBottomMm")
                        .HasColumnType("REAL");

                    b.Property<double>("MarginLeftMm")
                        .HasColumnType("REAL");

                    b.Property<double>("MarginRightMm")
                        .HasColumnType("REAL");

                    b.Property<double>("MarginTopMm")
                        .HasColumnType("REAL");

                    b.Property<double>("MinFontSizePt")
                        .HasColumnType("REAL");

                    b.Property<double>("PageHeightMm")
                        .HasColumnType("REAL");

                    b.Property<double>("PageWidthMm")
                        .HasColumnType("REAL");

                    b.Property<string>("PrimaryFontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityTopLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePersianDigits")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellPaddingMm = 1.2,
                            DefaultFontSizePt = 9.0,
                            GroupGapMm = 2.5,
                            GroupHeaderFontSizePt = 10.0,
                            HeaderFontSizePt = 16.0,
                            MarginBottomMm = 10.0,
                            MarginLeftMm = 8.0,
                            MarginRightMm = 8.0,
                            MarginTopMm = 10.0,
                            MinFontSizePt = 7.0,
                            PageHeightMm = 297.0,
                            PageWidthMm = 210.0,
                            PrimaryFontFamily = "Vazirmatn",
                            PriorityTopLimit = 3,
                            UsePersianDigits = true
                        });
                });

            modelBuilder.Entity("PhoneBook.Domain.Entities.DocumentHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocumentHeaders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "داخلی پرسنل شرکت رهیاب رایانه گستر",
                            UpdatedAt = new DateOnly(2026, 1, 1)
                        });
                });

            modelBuilder.Entity("PhoneBook.Domain.Entities.PhoneBookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("GroupId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("PhoneBookEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Extension = "۱۸۸",
                            GroupId = 1,
                            IsActive = true,
                            Name = "آقای جعفری"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Extension = "۱۹۶",
                            GroupId = 1,
                            IsActive = true,
                            Name = "خانم جهان‌نما"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Extension = "۱۹۳",
                            GroupId = 1,
                            IsActive = true,
                            Name = "خانم تقوائی"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Extension = "۱۹۵",
                            GroupId = 1,
                            IsActive = true,
                            Name = "خانم شمس"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Extension = "۱۹۴",
                            GroupId = 1,
                            IsActive = true,
                            Name = "خانم خیری"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Extension = "۱۹۸",
                            GroupId = 1,
                            IsActive = true,
                            Name = "خانم اردستانی"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            Extension = "۱۱۶",
                            GroupId = 2,
                            IsActive = true,
                            Name = "آقای علی نوربخش"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 2,
                            Extension = "۱۱۵",
                            GroupId = 2,
                            IsActive = true,
                            Name = "خانم سمانه مومن"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 3,
                            Extension = "۱۲۲",
                            GroupId = 2,
                            IsActive = true,
                            Name = "آقای احسان جعفری"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 4,
                            Extension = "۱۱۸",
                            GroupId = 2,
                            IsActive = true,
                            Name = "آقای علی گودرزی"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 5,
                            Extension = "۱۲۴",
                            GroupId = 2,
                            IsActive = true,
                            Name = "آقای مهرابی"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 6,
                            Extension = "۱۱۹",
                            GroupId = 2,
                            IsActive = true,
                            Name = "آقای افشار"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 7,
                            Extension = "۱۲۳",
                            GroupId = 2,
                            IsActive = true,
                            Name = "آقای صالحان"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 8,
                            Extension = "۱۲۵",
                            GroupId = 2,
                            IsActive = true,
                            Name = "آقای عبدالهی"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 9,
                            Extension = "۱۲۰",
                            GroupId = 2,
                            IsActive = true,
                            Name = "خانم جعفر کیاه"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 1,
                            Extension = "۱۵۹",
                            GroupId = 3,
                            IsActive = true,
                            Name = "آقای نوید نصیری"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 2,
                            Extension = "۱۶۱",
                            GroupId = 3,
                            IsActive = true,
                            Name = "آقای مهدی خانی"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 3,
                            Extension = "۱۸۱",
                            GroupId = 3,
                            IsActive = true,
                            Name = "آقای علی کامجو"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 4,
                            Extension = "۱۵۶",
                            GroupId = 3,
                            IsActive = true,
                            Name = "آقای محمدجواد کریمی راد"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 5,
                            Extension = "۱۶۷",
                            GroupId = 3,
                            IsActive = true,
                            Name = "آقای نصرت رنجبر"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 6,
                            Extension = "۱۵۵",
                            GroupId = 3,
                            IsActive = true,
                            Name = "آقای بهبهانی"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 7,
                            Extension = "۱۶۰",
                            GroupId = 3,
                            IsActive = true,
                            Name = "خانم مسناآبادی"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 8,
                            Extension = "۱۸۳",
                            GroupId = 3,
                            IsActive = true,
                            Name = "آقای سامانی"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 9,
                            Extension = "۱۸۵",
                            GroupId = 3,
                            IsActive = true,
                            Name = "خانم میرزا زاده"
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 1,
                            Extension = "۱۲۸",
                            GroupId = 4,
                            IsActive = true,
                            Name = "طبقه اول – علیرضا فتحی"
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 2,
                            Extension = "۲۴۱",
                            GroupId = 4,
                            IsActive = true,
                            Name = "طبقه دوم – آقای بهروز شیرآوند"
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 3,
                            Extension = "۳۱۷",
                            GroupId = 4,
                            IsActive = true,
                            Name = "طبقه سوم – آقای حسن شیرآوند"
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 4,
                            Extension = "۵۹۰",
                            GroupId = 4,
                            IsActive = true,
                            Name = ""
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 5,
                            Extension = "۶۱۳",
                            GroupId = 4,
                            IsActive = true,
                            Name = "طبقه ششم – آقای آیت شیراوند"
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 1,
                            Extension = "۲۰۴",
                            GroupId = 5,
                            IsActive = true,
                            Name = "خانم قائم مقامی"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 2,
                            Extension = "۲۴۳",
                            GroupId = 5,
                            IsActive = true,
                            Name = "خانم حامدی"
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 3,
                            Extension = "۲۴۲",
                            GroupId = 5,
                            IsActive = true,
                            Name = "خانم سلیمی"
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 4,
                            Extension = "۲۳۲",
                            GroupId = 5,
                            IsActive = true,
                            Name = "آقای مزدارانی"
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 5,
                            Extension = "۲۳۳",
                            GroupId = 5,
                            IsActive = true,
                            Name = "خانم نصیری زاده"
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 6,
                            Extension = "۲۲۱",
                            GroupId = 5,
                            IsActive = true,
                            Name = "آقای روحی"
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 7,
                            Extension = "۲۱۰",
                            GroupId = 5,
                            IsActive = true,
                            Name = "خانم خسروجردی"
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 8,
                            Extension = "۲۱۹",
                            GroupId = 5,
                            IsActive = true,
                            Name = "آقای نوروزی"
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 9,
                            Extension = "۲۲۲",
                            GroupId = 5,
                            IsActive = true,
                            Name = "بیژن راجی"
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 10,
                            Extension = "۲۲۸",
                            GroupId = 5,
                            IsActive = true,
                            Name = "خانم خزچین"
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 11,
                            Extension = "۲۳۱",
                            GroupId = 5,
                            IsActive = true,
                            Name = "آقای سعیدی نژاد"
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 1,
                            Extension = "۲۲۶",
                            GroupId = 6,
                            IsActive = true,
                            Name = ""
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 1,
                            Extension = "۱۳۴",
                            GroupId = 7,
                            IsActive = true,
                            Name = "آقای اسکندری"
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 1,
                            Extension = "۱۶۳",
                            GroupId = 8,
                            IsActive = true,
                            Name = "خانم نوربخش"
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 2,
                            Extension = "۱۹۷",
                            GroupId = 8,
                            IsActive = true,
                            Name = "خانم سلیمان پوریان"
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 1,
                            Extension = "۵۸۷",
                            GroupId = 9,
                            IsActive = true,
                            Name = "آقای عسگری"
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 1,
                            Extension = "۵۳۷",
                            GroupId = 10,
                            IsActive = true,
                            Name = "خانم صفری"
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 1,
                            Extension = "۵۸۴",
                            GroupId = 11,
                            IsActive = true,
                            Name = "آقای استقامتی"
                        },
                        new
                        {
                            Id = 48,
                            DisplayOrder = 2,
                            Extension = "۱۰۰",
                            GroupId = 11,
                            IsActive = true,
                            Name = "نگهبان"
                        },
                        new
                        {
                            Id = 49,
                            DisplayOrder = 1,
                            Extension = "۱۲۱",
                            GroupId = 12,
                            IsActive = true,
                            Name = ""
                        },
                        new
                        {
                            Id = 50,
                            DisplayOrder = 1,
                            Extension = "۶۰۱",
                            GroupId = 13,
                            IsActive = true,
                            Name = "خانم شاه محمدی"
                        },
                        new
                        {
                            Id = 51,
                            DisplayOrder = 2,
                            Extension = "۶۰۷ - ۶۰۶",
                            GroupId = 13,
                            IsActive = true,
                            Name = "آقای دکتر شعاعی"
                        },
                        new
                        {
                            Id = 52,
                            DisplayOrder = 3,
                            Extension = "۶۱۰",
                            GroupId = 13,
                            IsActive = true,
                            Name = "آقای باغستانی"
                        },
                        new
                        {
                            Id = 53,
                            DisplayOrder = 4,
                            Extension = "۶۰۳",
                            GroupId = 13,
                            IsActive = true,
                            Name = "آقای باقری"
                        },
                        new
                        {
                            Id = 54,
                            DisplayOrder = 5,
                            Extension = "۶۱۱",
                            GroupId = 13,
                            IsActive = true,
                            Name = "آقای دکتر فتحعلیزاده"
                        },
                        new
                        {
                            Id = 55,
                            DisplayOrder = 1,
                            Extension = "۳۰۸",
                            GroupId = 14,
                            IsActive = true,
                            Name = "آقای قلانی"
                        },
                        new
                        {
                            Id = 56,
                            DisplayOrder = 2,
                            Extension = "۳۰۷",
                            GroupId = 14,
                            IsActive = true,
                            Name = "خانم خردوار"
                        },
                        new
                        {
                            Id = 57,
                            DisplayOrder = 3,
                            Extension = "۳۰۵",
                            GroupId = 14,
                            IsActive = true,
                            Name = "آقای داود آبادی"
                        },
                        new
                        {
                            Id = 58,
                            DisplayOrder = 4,
                            Extension = "۳۰۶",
                            GroupId = 14,
                            IsActive = true,
                            Name = "خانم ذوالفقاری"
                        },
                        new
                        {
                            Id = 59,
                            DisplayOrder = 5,
                            Extension = "۳۰۴",
                            GroupId = 14,
                            IsActive = true,
                            Name = "خانم طهماسبی"
                        },
                        new
                        {
                            Id = 60,
                            DisplayOrder = 6,
                            Extension = "۳۱۶",
                            GroupId = 14,
                            IsActive = true,
                            Name = "آقای حبیبی"
                        },
                        new
                        {
                            Id = 61,
                            DisplayOrder = 7,
                            Extension = "۳۲۱",
                            GroupId = 14,
                            IsActive = true,
                            Name = "آقای احمدی زاده"
                        },
                        new
                        {
                            Id = 62,
                            DisplayOrder = 8,
                            Extension = "۳۰۹",
                            GroupId = 14,
                            IsActive = true,
                            Name = "آقای لطفی"
                        },
                        new
                        {
                            Id = 63,
                            DisplayOrder = 9,
                            Extension = "۳۱۹",
                            GroupId = 14,
                            IsActive = true,
                            Name = "خانم علی نقیان"
                        },
                        new
                        {
                            Id = 64,
                            DisplayOrder = 1,
                            Extension = "۴۰۲",
                            GroupId = 15,
                            IsActive = true,
                            Name = "آقای غریبی"
                        },
                        new
                        {
                            Id = 65,
                            DisplayOrder = 2,
                            Extension = "۴۰۳",
                            GroupId = 15,
                            IsActive = true,
                            Name = "خانم زندیه"
                        },
                        new
                        {
                            Id = 66,
                            DisplayOrder = 3,
                            Extension = "۴۰۱",
                            GroupId = 15,
                            IsActive = true,
                            Name = "آقای فیروزمنش"
                        },
                        new
                        {
                            Id = 67,
                            DisplayOrder = 4,
                            Extension = "۴۰۵",
                            GroupId = 15,
                            IsActive = true,
                            Name = "آقای بیداران"
                        },
                        new
                        {
                            Id = 68,
                            DisplayOrder = 5,
                            Extension = "۴۰۶",
                            GroupId = 15,
                            IsActive = true,
                            Name = "آقای ستاری کیا"
                        },
                        new
                        {
                            Id = 69,
                            DisplayOrder = 6,
                            Extension = "۴۰۴",
                            GroupId = 15,
                            IsActive = true,
                            Name = "آقای پور صدرا"
                        },
                        new
                        {
                            Id = 70,
                            DisplayOrder = 7,
                            GroupId = 15,
                            IsActive = true,
                            Name = "خانم نژاد عبداله"
                        },
                        new
                        {
                            Id = 71,
                            DisplayOrder = 1,
                            Extension = "۵۷۱",
                            GroupId = 16,
                            IsActive = true,
                            Name = "آقای خورش"
                        },
                        new
                        {
                            Id = 72,
                            DisplayOrder = 2,
                            Extension = "۵۷۳",
                            GroupId = 16,
                            IsActive = true,
                            Name = "خانم گرشاسبی"
                        },
                        new
                        {
                            Id = 73,
                            DisplayOrder = 3,
                            Extension = "۵۷۲",
                            GroupId = 16,
                            IsActive = true,
                            Name = "آقای عباسی"
                        },
                        new
                        {
                            Id = 74,
                            DisplayOrder = 4,
                            Extension = "۵۷۷",
                            GroupId = 16,
                            IsActive = true,
                            Name = "خانم خزائلی"
                        },
                        new
                        {
                            Id = 75,
                            DisplayOrder = 5,
                            Extension = "۵۳۸",
                            GroupId = 16,
                            IsActive = true,
                            Name = "خانم رحیمی"
                        },
                        new
                        {
                            Id = 76,
                            DisplayOrder = 1,
                            Extension = "۶۰۴",
                            GroupId = 17,
                            IsActive = true,
                            Name = ""
                        },
                        new
                        {
                            Id = 77,
                            DisplayOrder = 1,
                            Extension = "۶۰۹",
                            GroupId = 18,
                            IsActive = true,
                            Name = ""
                        },
                        new
                        {
                            Id = 78,
                            DisplayOrder = 1,
                            Extension = "۳۱۱",
                            GroupId = 19,
                            IsActive = true,
                            Name = ""
                        });
                });

            modelBuilder.Entity("PhoneBook.Domain.Entities.PhoneBookGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("KeepTogether")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int?>("PreferredColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.ToTable("PhoneBookGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 0,
                            Priority = 1,
                            Required = true,
                            Title = "فروش"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 0,
                            Priority = 4,
                            Required = true,
                            Title = "نرم‌افزار پیام کوتاه"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 0,
                            Priority = 7,
                            Required = true,
                            Title = "پشتیبانی پیام کوتاه"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 0,
                            Priority = 9,
                            Required = true,
                            Title = "آبدارخانه"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 1,
                            Priority = 2,
                            Required = true,
                            Title = "لجستیک"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 1,
                            Priority = 10,
                            Required = true,
                            Title = "سامانه‌های عمومی"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 1,
                            Priority = 11,
                            Required = true,
                            Title = "تست و تضمین کیفیت"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 1,
                            Priority = 12,
                            Required = true,
                            Title = "طراحی محصول"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 1,
                            Priority = 13,
                            Required = true,
                            Title = "امور قراردادها"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 1,
                            Priority = 14,
                            Required = true,
                            Title = "دبیرخانه"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 1,
                            Priority = 15,
                            Required = true,
                            Title = "حراست"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 1,
                            Priority = 16,
                            Required = true,
                            Title = "اسکرام مستر"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 2,
                            Priority = 3,
                            Required = true,
                            Title = "مدیریت"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 2,
                            Priority = 5,
                            Required = true,
                            Title = "واحد مالی"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 2,
                            Priority = 6,
                            Required = true,
                            Title = "واحد IT"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 2,
                            Priority = 8,
                            Required = true,
                            Title = "واحد منابع انسانی"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 2,
                            Priority = 17,
                            Required = true,
                            Title = "اتاق مشاوران"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 2,
                            Priority = 18,
                            Required = true,
                            Title = "اتاق کنفرانس طبقه ۶"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            IsActive = true,
                            KeepTogether = true,
                            PreferredColumn = 2,
                            Priority = 19,
                            Required = true,
                            Title = "اتاق جلسات طبقه ۳"
                        });
                });

            modelBuilder.Entity("PhoneBook.Domain.Entities.PhoneBookEntry", b =>
                {
                    b.HasOne("PhoneBook.Domain.Entities.PhoneBookGroup", "Group")
                        .WithMany("Entries")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PhoneBook.Domain.Entities.PhoneBookGroup", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
